# Generated by Django 4.2.15 on 2024-09-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturetodo',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
